//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentApp.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public int id { get; set; }
        public int team_id_home { get; set; }
        public int team_id_away { get; set; }
        public sbyte score_home { get; set; }
        public sbyte score_away { get; set; }
        public int tournament_id { get; set; }
    
        public virtual team team { get; set; }
        public virtual team team1 { get; set; }
        public virtual tournament tournament { get; set; }
    }
}
